//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group12_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonAdminUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NonAdminUser()
        {
            this.Transaction = new HashSet<Transaction>();
        }
    
        public string ID { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string AdministratorID { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual UserPassword UserPassword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
