//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group12_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLine
    {
        public string ID { get; set; }
        public decimal creditedAmount { get; set; }
        public decimal debitedAmount { get; set; }
        public string comment { get; set; }
        public string TransactionID { get; set; }
        public string FirstMasterAccountID { get; set; }
        public string SecondMasterAccountID { get; set; }
    
        public virtual MasterAccount MasterAccount { get; set; }
        public virtual MasterAccount MasterAccount1 { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
